import { contextBridge, ipcRenderer } from 'electron';
import type { Bridge } from '../shared/types';

/**
 * The only surface the renderer can reach. Context isolation stays on and no
 * Node primitive is forwarded; every call is an explicit, named channel.
 */
const bridge: Bridge = {
  platform: process.platform,
  isElevated: () => ipcRenderer.invoke('system:elevated'),
  loadCatalog: () => ipcRenderer.invoke('catalog:load'),
  window: (action) => ipcRenderer.send('window:action', action),
  run: (kind, ids) => ipcRenderer.invoke('winutil:run', kind, ids),
  installed: () => ipcRenderer.invoke('winutil:installed'),
  ensureDeps: () => ipcRenderer.invoke('deps:ensure'),
  onProgress: (cb) => { ipcRenderer.on('winutil:progress', (_e, p) => cb(p)); },
  loadOfflineDocs: () => ipcRenderer.invoke('docs:bundle'),
  loadChangelog: () => ipcRenderer.invoke('changelog:load'),
  openExternal: (url) => ipcRenderer.invoke('docs:open-external', url),
  exportView: (payload) => ipcRenderer.invoke('view:export', payload),
  openExportInVSCode: (filePath) => ipcRenderer.invoke('view:export-open-vscode', filePath),
  readPrefs: () => ipcRenderer.invoke('prefs:read'),
  writePrefs: (prefs) => ipcRenderer.invoke('prefs:write', prefs),
  notificationsState: () => ipcRenderer.invoke('notifications:state'),
  notificationsAdd: (input) => ipcRenderer.invoke('notifications:add', input),
  notificationsReview: (ids, review) => ipcRenderer.invoke('notifications:review', ids, review),
  notificationsDelete: (ids) => ipcRenderer.invoke('notifications:delete', ids),
  onNotificationsState: (callback) => { ipcRenderer.on('notifications:state', (_event, state) => callback(state)); },
  history: () => ipcRenderer.invoke('history:read'),
  appendHistory: (entry) => ipcRenderer.invoke('history:append', entry),
  historyAccess: () => ipcRenderer.invoke('history:access'),
  historyConfigureCredential: (password) => ipcRenderer.invoke('history:configure-credential', password),
  historyUnlock: (password) => ipcRenderer.invoke('history:unlock', password),
  historyLock: () => ipcRenderer.invoke('history:lock'),
  historyBrowse: (query) => ipcRenderer.invoke('history:browse', query),
  historyDiff: (left, right) => ipcRenderer.invoke('history:diff', left, right),
  historyRestore: (revision) => ipcRenderer.invoke('history:restore', revision),
  historyLabel: (revision, label) => ipcRenderer.invoke('history:label', revision, label),
  historyPrune: (keep) => ipcRenderer.invoke('history:prune', keep),
  historyExport: (query) => ipcRenderer.invoke('history:export', query),
  updateStatus: () => ipcRenderer.invoke('update:status'),
  checkForUpdates: () => ipcRenderer.invoke('update:check'),
  cancelUpdateCheck: () => ipcRenderer.invoke('update:cancel'),
  deferUpdate: () => ipcRenderer.invoke('update:defer'),
  restartToUpdate: (request) => ipcRenderer.invoke('update:restart', request),
  onUpdateStatus: (cb) => { ipcRenderer.on('update:status', (_e, status) => cb(status)); },
  authenticatorBegin: (request) => ipcRenderer.invoke('authenticator:begin', request),
  authenticatorImportPngFile: () => ipcRenderer.invoke('authenticator:import-png-file'),
  authenticatorImportClipboardPng: () => ipcRenderer.invoke('authenticator:import-clipboard-png'),
  authenticatorConfirm: (registrationId, code) => ipcRenderer.invoke('authenticator:confirm', registrationId, code),
  authenticatorCancel: (registrationId) => ipcRenderer.invoke('authenticator:cancel', registrationId),
  authenticatorList: () => ipcRenderer.invoke('authenticator:list'),
  authenticatorCodes: (id) => ipcRenderer.invoke('authenticator:codes', id),
  authenticatorRemove: (id) => ipcRenderer.invoke('authenticator:remove', id),
  lockState: (surfaceId) => ipcRenderer.invoke('locks:state', surfaceId),
  lockPrepareTotp: (label, account) => ipcRenderer.invoke('locks:prepare-totp', label, account),
  lockCreate: (request) => ipcRenderer.invoke('locks:create', request),
  lockUpdate: (lockId, request) => ipcRenderer.invoke('locks:update', lockId, request),
  lockRemove: (lockId) => ipcRenderer.invoke('locks:remove', lockId),
  lockSearch: (request) => ipcRenderer.invoke('locks:search', request),
  lockUnlock: (lockId, credential, surfaceId) => ipcRenderer.invoke('locks:unlock', lockId, credential, surfaceId),
  lockRelock: (lockId) => ipcRenderer.invoke('locks:relock', lockId),
  lockRecovery: () => ipcRenderer.invoke('locks:recovery'),
  lockOpenRecoveryFolder: () => ipcRenderer.invoke('locks:open-recovery-folder'),
  personalVocabularyLoad: () => ipcRenderer.invoke('personal-vocabulary:load'),
  personalVocabularyUpload: (payload) => ipcRenderer.invoke('personal-vocabulary:upload', payload),
  personalVocabularyClear: () => ipcRenderer.invoke('personal-vocabulary:clear'),
  narrationState: () => ipcRenderer.invoke('narration:state'),
  narrate: (event) => ipcRenderer.invoke('narration:enqueue', event),
  stopNarration: () => ipcRenderer.invoke('narration:stop'),
  onNarrationSpeech: (cb) => { ipcRenderer.on('narration:speech', (_e, request) => cb(request)); },
  onNarrationCancel: (cb) => { ipcRenderer.on('narration:cancel', (_e, request) => cb(request)); },
  narrationSpeechResult: (id, ok, error) => ipcRenderer.send('narration:speech-result', id, ok, error),
  onNarrationState: (cb) => { ipcRenderer.on('narration:state', (_e, state) => cb(state)); },
  settingsSurfaceState: () => ipcRenderer.invoke('settings-surface:state'),
  renameDisplayName: (displayName) => ipcRenderer.invoke('display-name:rename', displayName),
  resetDisplayName: () => ipcRenderer.invoke('display-name:reset'),
  setDialogEmojis: (enabled) => ipcRenderer.invoke('dialog-emoji:set', enabled),
  renameSchoolMode: (displayLabel) => ipcRenderer.invoke('school-mode:rename', displayLabel),
  configureSchoolModePassword: (password) => ipcRenderer.invoke('school-mode:configure-password', password),
  resetSchoolModeCredential: () => ipcRenderer.invoke('school-mode:reset-credential'),
  setSchoolModeEnabled: (enabled, password) => ipcRenderer.invoke('school-mode:set-enabled', enabled, password),
  onSettingsSurfaceState: (cb) => { ipcRenderer.on('settings-surface:state', (_e, state) => cb(state)); },
  scheduledSettingsState: () => ipcRenderer.invoke('scheduled-settings:state'),
  saveScheduledSettings: (document) => ipcRenderer.invoke('scheduled-settings:save', document),
  refreshScheduledSettings: () => ipcRenderer.invoke('scheduled-settings:refresh'),
  setScheduledHomeAssistantToken: (ruleId, token) => ipcRenderer.invoke('scheduled-settings:set-ha-token', ruleId, token),
  clearScheduledHomeAssistantToken: (ruleId) => ipcRenderer.invoke('scheduled-settings:clear-ha-token', ruleId),
  onScheduledSettingsState: (cb) => { ipcRenderer.on('scheduled-settings:state', (_e, state) => cb(state)); },
  dimSumStartup: () => ipcRenderer.invoke('dim-sum:startup'),
  fileConverterState: () => ipcRenderer.invoke('file-converter:state'),
  fileConverterPickSources: () => ipcRenderer.invoke('file-converter:pick-sources'),
  fileConverterPickOutputDestination: () => ipcRenderer.invoke('file-converter:pick-output-destination'),
  fileConverterClearOutputDestination: () => ipcRenderer.invoke('file-converter:clear-output-destination'),
  fileConverterClearSelection: () => ipcRenderer.invoke('file-converter:clear-selection'),
  fileConverterEnqueue: (adapterId) => ipcRenderer.invoke('file-converter:enqueue', adapterId),
  fileConverterPause: () => ipcRenderer.invoke('file-converter:pause'),
  fileConverterResume: () => ipcRenderer.invoke('file-converter:resume'),
  fileConverterCancelAll: () => ipcRenderer.invoke('file-converter:cancel-all'),
  fileConverterRetryFailed: () => ipcRenderer.invoke('file-converter:retry-failed'),
  fileConverterResetQueue: () => ipcRenderer.invoke('file-converter:reset-queue'),
  appLogoState: () => ipcRenderer.invoke('app-logo:state'),
  appLogoPickPng: (transform) => ipcRenderer.invoke('app-logo:pick-png', transform),
  appLogoSelectPreset: (presetId, transform) => ipcRenderer.invoke('app-logo:select-preset', presetId, transform),
  appLogoUpdateTransform: (transform) => ipcRenderer.invoke('app-logo:update-transform', transform),
  appLogoReset: () => ipcRenderer.invoke('app-logo:reset'),
  workspaceState: () => ipcRenderer.invoke('workspace:state'),
  workspaceSave: (state) => ipcRenderer.invoke('workspace:save', state),
  selectionProfilesList: () => ipcRenderer.invoke('selection-profiles:list'),
  selectionProfilesCreate: (request) => ipcRenderer.invoke('selection-profiles:create', request),
  selectionProfilesMigrate: (request) => ipcRenderer.invoke('selection-profiles:migrate', request),
  selectionProfilesUpdate: (id, request) => ipcRenderer.invoke('selection-profiles:update', id, request),
  selectionProfilesDelete: (ids) => ipcRenderer.invoke('selection-profiles:delete', ids),
  appearanceThemeList: () => ipcRenderer.invoke('appearance-theme:list'),
  appearanceThemeCreate: (name, theme) => ipcRenderer.invoke('appearance-theme:create', name, theme),
  appearanceThemeApply: (id) => ipcRenderer.invoke('appearance-theme:apply', id),
  appearanceThemeReset: () => ipcRenderer.invoke('appearance-theme:reset'),
  appearanceThemeDelete: (id) => ipcRenderer.invoke('appearance-theme:delete', id),
  appearanceThemeImport: () => ipcRenderer.invoke('appearance-theme:import'),
  appearanceThemeExport: (id) => ipcRenderer.invoke('appearance-theme:export', id),
  ollamaHealth: () => ipcRenderer.invoke('ollama:health'),
  ollamaInstalledEnrichment: () => ipcRenderer.invoke('ollama:installed-enrichment'),
  ollamaRefreshInstalledEnrichment: () => ipcRenderer.invoke('ollama:refresh-installed-enrichment'),
  ollamaHardware: () => ipcRenderer.invoke('ollama:hardware'),
  ollamaCatalog: () => ipcRenderer.invoke('ollama:catalog'),
  ollamaRefreshCatalog: () => ipcRenderer.invoke('ollama:refresh-catalog'),
  ollamaPullQueue: () => ipcRenderer.invoke('ollama:pull-queue'),
  ollamaEnqueuePulls: (models) => ipcRenderer.invoke('ollama:enqueue-pulls', models),
  ollamaCancelPull: (model) => ipcRenderer.invoke('ollama:cancel-pull', model),
  ollamaRetryPull: (model) => ipcRenderer.invoke('ollama:retry-pull', model),
  ollamaPickChatAttachment: (model) => ipcRenderer.invoke('ollama:pick-chat-attachment', model),
  ollamaClearChatAttachment: (id) => ipcRenderer.invoke('ollama:clear-chat-attachment', id),
  ollamaChat: (request, variant) => ipcRenderer.invoke('ollama:chat', request, variant),
  ollamaCancelChat: () => ipcRenderer.invoke('ollama:cancel-chat'),
  ollamaExportChat: (request) => ipcRenderer.invoke('ollama:export-chat', request),
  ollamaChatSessionList: (request) => ipcRenderer.invoke('ollama:chat-session-list', request),
  ollamaChatSessionGet: (request) => ipcRenderer.invoke('ollama:chat-session-get', request),
  ollamaChatSessionCreate: (request) => ipcRenderer.invoke('ollama:chat-session-create', request),
  ollamaChatSessionUpdate: (request) => ipcRenderer.invoke('ollama:chat-session-update', request),
  ollamaChatSessionRename: (request) => ipcRenderer.invoke('ollama:chat-session-rename', request),
  ollamaChatSessionDelete: (request) => ipcRenderer.invoke('ollama:chat-session-delete', request),
  ollamaHarnessExecutables: (profileId) => ipcRenderer.invoke('ollama:harness-executables', profileId),
  ollamaHarnessPickWorkspace: () => ipcRenderer.invoke('ollama:harness-pick-workspace'),
  ollamaHarnessPreflight: (request) => ipcRenderer.invoke('ollama:harness-preflight', request),
  ollamaHarnessLaunch: (plan) => ipcRenderer.invoke('ollama:harness-launch', plan),
  ollamaHarnessRestore: (plan) => ipcRenderer.invoke('ollama:harness-restore', plan),
  onOllamaPullProgress: (cb) => { ipcRenderer.on('ollama:pull-progress', (_e, progress) => cb(progress)); },
  onOllamaChatChunk: (cb) => { ipcRenderer.on('ollama:chat-chunk', (_e, content) => cb(content)); },
};

contextBridge.exposeInMainWorld('winutil', bridge);
