import { contextBridge, ipcRenderer } from 'electron';
import type { Bridge } from '../shared/types';

/**
 * The only surface the renderer can reach. Context isolation stays on and no
 * Node primitive is forwarded; every call is an explicit, named channel.
 */
const bridge: Bridge = {
  platform: process.platform,
  isElevated: () => ipcRenderer.invoke('system:elevated'),
  loadCatalog: () => ipcRenderer.invoke('catalog:load'),
  window: (action) => ipcRenderer.send('window:action', action),
  run: (kind, ids) => ipcRenderer.invoke('winutil:run', kind, ids),
  installed: () => ipcRenderer.invoke('winutil:installed'),
  ensureDeps: () => ipcRenderer.invoke('deps:ensure'),
  onProgress: (cb) => { ipcRenderer.on('winutil:progress', (_e, p) => cb(p)); },
  openExternal: () => undefined,
  exportView: (payload) => ipcRenderer.invoke('view:export', payload),
  openExportInVSCode: (filePath) => ipcRenderer.invoke('view:export-open-vscode', filePath),
  readPrefs: () => ipcRenderer.invoke('prefs:read'),
  writePrefs: (prefs) => ipcRenderer.invoke('prefs:write', prefs),
  history: () => ipcRenderer.invoke('history:read'),
  appendHistory: (entry) => ipcRenderer.invoke('history:append', entry),
  historyAccess: () => ipcRenderer.invoke('history:access'),
  historyConfigureCredential: (password) => ipcRenderer.invoke('history:configure-credential', password),
  historyUnlock: (password) => ipcRenderer.invoke('history:unlock', password),
  historyLock: () => ipcRenderer.invoke('history:lock'),
  historyBrowse: (query) => ipcRenderer.invoke('history:browse', query),
  historyDiff: (left, right) => ipcRenderer.invoke('history:diff', left, right),
  historyRestore: (revision) => ipcRenderer.invoke('history:restore', revision),
  historyLabel: (revision, label) => ipcRenderer.invoke('history:label', revision, label),
  historyPrune: (keep) => ipcRenderer.invoke('history:prune', keep),
  historyExport: (query) => ipcRenderer.invoke('history:export', query),
  updateStatus: () => ipcRenderer.invoke('update:status'),
  checkForUpdates: () => ipcRenderer.invoke('update:check'),
  restartToUpdate: () => ipcRenderer.send('update:restart'),
  onUpdateStatus: (cb) => { ipcRenderer.on('update:status', (_e, status) => cb(status)); },
  authenticatorBegin: (request) => ipcRenderer.invoke('authenticator:begin', request),
  authenticatorConfirm: (registrationId, code) => ipcRenderer.invoke('authenticator:confirm', registrationId, code),
  authenticatorCancel: (registrationId) => ipcRenderer.invoke('authenticator:cancel', registrationId),
  authenticatorList: () => ipcRenderer.invoke('authenticator:list'),
  authenticatorCodes: (id) => ipcRenderer.invoke('authenticator:codes', id),
  authenticatorRemove: (id) => ipcRenderer.invoke('authenticator:remove', id),
  personalVocabularyLoad: () => ipcRenderer.invoke('personal-vocabulary:load'),
  personalVocabularyUpload: (payload) => ipcRenderer.invoke('personal-vocabulary:upload', payload),
  personalVocabularyClear: () => ipcRenderer.invoke('personal-vocabulary:clear'),
  narrationState: () => ipcRenderer.invoke('narration:state'),
  narrate: (event) => ipcRenderer.invoke('narration:enqueue', event),
  stopNarration: () => ipcRenderer.invoke('narration:stop'),
  onNarrationSpeech: (cb) => { ipcRenderer.on('narration:speech', (_e, request) => cb(request)); },
  onNarrationCancel: (cb) => { ipcRenderer.on('narration:cancel', (_e, request) => cb(request)); },
  narrationSpeechResult: (id, ok, error) => ipcRenderer.send('narration:speech-result', id, ok, error),
  onNarrationState: (cb) => { ipcRenderer.on('narration:state', (_e, state) => cb(state)); },
  settingsSurfaceState: () => ipcRenderer.invoke('settings-surface:state'),
  renameDisplayName: (displayName) => ipcRenderer.invoke('display-name:rename', displayName),
  resetDisplayName: () => ipcRenderer.invoke('display-name:reset'),
  setDialogEmojis: (enabled) => ipcRenderer.invoke('dialog-emoji:set', enabled),
  renameSchoolMode: (displayLabel) => ipcRenderer.invoke('school-mode:rename', displayLabel),
  configureSchoolModePassword: (password) => ipcRenderer.invoke('school-mode:configure-password', password),
  resetSchoolModeCredential: () => ipcRenderer.invoke('school-mode:reset-credential'),
  setSchoolModeEnabled: (enabled, password) => ipcRenderer.invoke('school-mode:set-enabled', enabled, password),
  onSettingsSurfaceState: (cb) => { ipcRenderer.on('settings-surface:state', (_e, state) => cb(state)); },
};

contextBridge.exposeInMainWorld('winutil', bridge);
